### ISSUE TITLE
フィードバック

### ISSUE THREAD

**Issue by ozelotjp** [ozelotjp/ShareWallet#33]
▼良かった点（Good）

- 開発環境がとてもリッチ
- コミットメッセージを「commitizen」が使うなどして読みやすいものにしている
- コミットの粒度も細かくて良い
- TypeScript でしっかり型を定義している
- デプロイも含めて色々なものを自動化していてGooD
- firebase.rule で権限をしっかり定義している
- 全体的に可読性が高い

▼機会点（Next）

- [ ] #34 招待リンクを削除した際に、削除をした旨のダイアログが表示されますが、画面上では何も変化がなかった（自動で招待のモーダルが閉じるとか、モーダル上のリンクが表示されなくなると良いかと）
- [ ] #35 docker の nodejs のイメージが、nodejs v10 だったので、なるべく LTS である v12 系を使うことが望ましい
- [ ] #36 ログイン画面のメールアドレス・パスワードの入力条件を表示する
- [ ] #36 ログイン画面のメールアドレス・パスワードが未入力の場合は、ログインボタンを非活性化する
- [ ] #36 ログイン画面の入力ボックスに何も入力せずログインボタンをクリックしてもエラーメッセージが表示されなかったので設定する
- [ ] #37 favicon を設定する
- [ ] #38 CSS スタイリングにも多少こだわって欲しい

---

▼良かった点(Good)

- コードが読みやすい
- コンポーネントが分かれており保守しやすい形になっている
- 環境変数で外部からfirebase等の設定値を指定することができる
- Gitのコミット粒度とコミットメッセージが良い感じ
- LinterやFormatterが整備されている
- VSCode + Remote Development (Container) ですぐに開発ができる状態になっている
- GitHub Actionsでデプロイが自動化されている

▼機会点(Next)

- [ ] #39 setup関数が長くなりがちなので、Vue (Nuxt)固有ではない部分は別の関数に切り出すなどするとよりGood

**Comment by ozelotjp** [comment]
機会点はすべて他のIssueに分離したのでこっちはCloseしましょ。
良かった点を忘れたときに見返せるように、このIssueのことを忘れないようにしなければ。
